### ISSUE TITLE
Application for LankyBox01

### ISSUE THREAD

**Issue by ghost** [MobSpot/Code4Covid#1]
Hello! I would like to join as a Core Website Developer! Are there any requirements before i could join? I hope not.

**Comment by ghost** [comment]
Also, i have this small design i made a few months ago, is it good?
https://blush-juvenile-eyebrow.glitch.me/

**Comment by rockstarrudy** [comment]
I think you need too know html and css

**Comment by ghost** [comment]
> I think you have to know html and css

I know both of them, and you don't "i think" at me, ok?

**Comment by rockstarrudy** [comment]
> I know both of them, and you don't "i think" at me, ok?

why?
I am not trying to say it in a mean way.

**Comment by ghost** [comment]
> > I know both of them, and you don't "i think" at me, ok?
> 
> why?
> I am not trying to say it in a mean way.

Me neither, just please don't assume things when you're not sure

**Comment by rockstarrudy** [comment]
Oh okay, I was just guessing. Beacuse almost every site uses html and css

**Comment by ghost** [comment]
> Oh okay, I was just guessing. Beacuse almost every site uses html and css

How else would you make a site? Lol

**Comment by rockstarrudy** [comment]
lol

**Comment by dispherical** [comment]
@LankyBox01 Well, you have to make a site about COVID-19, then publish it. There are other places to help other than making websites, like Application Manager.

**Comment by ghost** [comment]
@aboutDavid I was just waiting for you, is this good:
https://blush-juvenile-eyebrow.glitch.me/
I can improve it WAY better

**Comment by dispherical** [comment]
> @aboutDavid I was just waiting for you, is this good:
> https://blush-juvenile-eyebrow.glitch.me/
> I can improve it WAY better

Well, you are not making the website (That's Core Website Designer), but yes, that is good.

**Comment by ghost** [comment]
> > @aboutDavid I was just waiting for you, is this good:
> > https://blush-juvenile-eyebrow.glitch.me/
> > I can improve it WAY better
> 
> Well, you are not making the website (That's Core Website Designer), but yes, that is good.

I AM applying for core website designer... cuz i can't really use javascript, nodejs, and other advanced programming launguages

**Comment by dispherical** [comment]
> I AM applying for core website designer.

Oh, the website is made using Markdown. But yes, you are accepted.

**Comment by ghost** [comment]
> > I AM applying for core website designer.
> 
> Oh, the website is made using Markdown. But yes, you are accepted.

Yay!

**Comment by dispherical** [comment]
I'll invite you to the organization so you can edit the website.
