### ISSUE TITLE
Application for codersuntited

### ISSUE THREAD

**Issue by rockstarrudy** [MobSpot/Code4Covid#2]
Could I help with coding. I would like to be a core web dev.
I know the following programming languages:

HTML
CSS
JS
NODE JS
@aboutDavid

**Comment by ghost** [comment]
a Website Maker?

**Comment by rockstarrudy** [comment]
@LankyBox01 I meant to say core webdev

**Comment by ghost** [comment]
> @LankyBox01 I meant to say core webdev

Go ahead and edit your post then.

**Comment by rockstarrudy** [comment]
@LankyBox01 that's what I did! 👍

**Comment by dispherical** [comment]
What is your Glitch username? @codersuntited

**Comment by rockstarrudy** [comment]
one sec

btw I am new to glitch

**Comment by rockstarrudy** [comment]
I made my account last week, but I still know programming.

**Comment by dispherical** [comment]
> I made my account last week, but I still know programming.

That is fine.

**Comment by oldalt** [comment]
Can i join

**Comment by oldalt** [comment]
@Code_ on glitch

**Comment by rockstarrudy** [comment]
@aboutDavid its called Cheezits

**Comment by rockstarrudy** [comment]
@code-alt make a new thread/issue

**Comment by rockstarrudy** [comment]
@aboutDavid is my submission accepted?

**Comment by rockstarrudy** [comment]
> What is your Glitch username? @codersuntited

Cheezits
@aboutDavid

**Comment by dispherical** [comment]
@code-alt Yes, please make a new issue.

**Comment by rockstarrudy** [comment]
@aboutDavid what coding Langs does the site use?

**Comment by dispherical** [comment]
> @aboutDavid what coding Langs does the site use?

Markdown and Jekyll.
The main site is located in README.md

**Comment by rockstarrudy** [comment]
@aboutDavid 

fyi: I am applying for core web creator

**Comment by rockstarrudy** [comment]
> > @aboutDavid what coding Langs does the site use?
> 
> Markdown and Jekyll.
> The main site is located in README.md

why not use html?

**Comment by rockstarrudy** [comment]
Am I accepted as dev?

**Comment by dispherical** [comment]
> why not use html?

Markdown uses HTML and Markdown is used for people who don't know how to code that much.

**Comment by rockstarrudy** [comment]
@aboutDavid do you know html?

**Comment by rockstarrudy** [comment]
if you think about it markdown isnt really coding

**Comment by rockstarrudy** [comment]
@aboutDavid can you also tell me if I am accepted?

**Comment by dispherical** [comment]
> @aboutDavid do you know html?

Yes. I made it so that way anybody can make the main website

**Comment by rockstarrudy** [comment]
@aboutDavid can you also tell me if I am accepted?

**Comment by dispherical** [comment]
> @aboutDavid can you also tell me if I am accepted?

We use JavaScript for the Web Workers and the webring.

**Comment by rockstarrudy** [comment]
@aboutDavid can I still use html?

**Comment by dispherical** [comment]
> @aboutDavid can you also tell me if I am accepted?

Also, please be patient.

**Comment by rockstarrudy** [comment]
@aboutDavid sorry.

**Comment by dispherical** [comment]
> @aboutDavid sorry.

That's fine.

**Comment by rockstarrudy** [comment]
@aboutDavid thanks!

**Comment by dispherical** [comment]
You are accepted, but please accept the invitation to join the team. You can edit the website if you join the team.

**Comment by rockstarrudy** [comment]
also should I make a forum for code4covid @aboutDavid

**Comment by rockstarrudy** [comment]
> You are accepted, but please accept the invitation to join the team. You can edit the website if you join the team.

the team on GitHub or on glitch? @aboutDavid

**Comment by dispherical** [comment]
> > You are accepted, but please accept the invitation to join the team. You can edit the website if you join the team.
> 
> the team on GitHub or on glitch? @aboutDavid

GitHub.

**Comment by rockstarrudy** [comment]
okay

**Comment by dispherical** [comment]
> also should I make a forum for code4covid @aboutDavid

No, I am already setting it up.

**Comment by rockstarrudy** [comment]
okay, I am guessing code4covid.flarum.cloud right? @aboutDavid

**Comment by dispherical** [comment]
> okay, I am guessing code4covid.flarum.cloud right?

No. It will be at forum.code4covid.xyz (I am still setting it up.)

**Comment by rockstarrudy** [comment]
why dont you apply for discourse? @aboutDavid

**Comment by rockstarrudy** [comment]
Also I think we should use just html. (in my opinion)

**Comment by rockstarrudy** [comment]
@aboutDavid what forum are we using?

**Comment by rockstarrudy** [comment]
do you have a vps? and If you do why not use discourse?

**Comment by dispherical** [comment]
> why dont you apply for discourse? @aboutDavid

Where do I apply then?

**Comment by dispherical** [comment]
I'm merging this with that issue.
