### ISSUE TITLE
forum

### ISSUE THREAD

**Issue by rockstarrudy** [MobSpot/Code4Covid#4]
This is confusing?
Are we using code4covid.flarum.cloud or forum.code4covid.xyz ? and why dont we use discourse! I can apply for it if you want 

@aboutDavid 
@LankyBox01

**Comment by ghost** [comment]
![uhh.. we've got a problem](http://u.cubeupload.com/LankyBox01/1y4rdZ.png)

**Comment by rockstarrudy** [comment]
@aboutDavid and @LankyBox01 lets go to the other issue
