### ISSUE TITLE
Which Forum to use?

### ISSUE THREAD

**Issue by dispherical** [MobSpot/Code4Covid#5]
why dont you apply for discourse? @aboutDavid

_Originally posted by @codersuntited in https://github.com/Code4Covid/Code4Covid/issues/2#issuecomment-683837527_

**Comment by dispherical** [comment]
@Code4Covid/website-coder So, we were talking about forums and we need to know what forum do we use?

**Comment by rockstarrudy** [comment]
@aboutDavid how bout discourse?

**Comment by rockstarrudy** [comment]
if your project is open source we can apply for it

**Comment by ghost** [comment]
> @aboutDavid how bout discourse?

Many cons on that.

- It is really heavy, the website will take really long time to load
- You have to pay if not
- You need to make an individual account
- It is very hard setting up

**Comment by dispherical** [comment]
> if your project is open source we can apply for it

The thing is, I don't know where to apply.

**Comment by rockstarrudy** [comment]
@aboutDavid do you have a vps?

**Comment by dispherical** [comment]
> @aboutDavid do you have a vps?

I have a RaspberryPi.

**Comment by ghost** [comment]
However, [this](https://code4covid.flarum.cloud/), also has a few pros

- You don't need to make an individual account - you can use your github/discord account
- It's translated in many launguages

**Comment by rockstarrudy** [comment]
@aboutDavid 
do you know how to self host discourse?

**Comment by rockstarrudy** [comment]
@aboutDavid I think discourse is the appropriate forum

**Comment by rockstarrudy** [comment]
@aboutDavid if you cant self host it apply for discourse at free.discourse.group
but before you do that read the rules

**Comment by dispherical** [comment]
> However, [this](https://code4covid.flarum.cloud/), also has a few pros
> 
> * You don't need to make an individual account - you can use your github/discord account
> * It's translated in many launguages

I'm not using flarum.cloud, I will self host it tho.

**Comment by rockstarrudy** [comment]
@aboutDavid apply for it! or should I?

**Comment by dispherical** [comment]
> @aboutDavid if you cant self host it apply for discourse at free.discourse.group
> but before you do that read the rules

Ok, let me read.

**Comment by rockstarrudy** [comment]
@aboutDavid how about we apply for it and if the deny we can use flarum

**Comment by rockstarrudy** [comment]
@aboutDavid should I apply?

**Comment by ghost** [comment]
> @aboutDavid how about we apply for it and if the deny we can use flarum

mostly denied because.. **YOU NEED A BUSINESS LICENSE**
and it costs.. money

**Comment by rockstarrudy** [comment]
@LankyBox01 no you dont. where does it say that

**Comment by rockstarrudy** [comment]
@aboutDavid what do u say?

**Comment by dispherical** [comment]
> @aboutDavid what do u say?

I don't know why you locked it, but most likely Flarum self hosted.

**Comment by ghost** [comment]
you need to be approved by law to be non-profit
smh

**Comment by ghost** [comment]
and you need a bussines license to do that

**Comment by rockstarrudy** [comment]
@LankyBox01 we aren't non profit we are open source

**Comment by rockstarrudy** [comment]
@aboutDavid what if you host discourse!

**Comment by ghost** [comment]
> @LankyBox01 we aren't non profit we are open source

Fine.

**Comment by rockstarrudy** [comment]
?

**Comment by dispherical** [comment]
It's most likely Flarum.

**Comment by rockstarrudy** [comment]
@aboutDavid okay

**Comment by rockstarrudy** [comment]
@aboutDavid but if you feel like you need discourse just tell me! I can apply for it!

**Comment by ghost** [comment]
> It's most likely Flarum.

is that a yes or a no?

**Comment by rockstarrudy** [comment]
I still think discourse is better

**Comment by ghost** [comment]
> I still think discourse is better

https://www.youtube.com/watch?v=oHC1230OpOg

**Comment by dispherical** [comment]
Ok, so it will be Flarum.

**Comment by ghost** [comment]
> Ok, so it will be Flarum.

The one i made or another one?

**Comment by rockstarrudy** [comment]
why?

**Comment by dispherical** [comment]
> > Ok, so it will be Flarum.
> 
> The one i made or another one?

Self hosted, sorry.

**Comment by ghost** [comment]
> > > Ok, so it will be Flarum.
> > 
> > 
> > The one i made or another one?
> 
> Self hosted, sorry.

oh.. ok!

**Comment by dispherical** [comment]
> why?

Because Flarum is less advanced for new users.

**Comment by rockstarrudy** [comment]
okay

**Comment by rockstarrudy** [comment]
@aboutDavid but can we plz use html for the site
