### ISSUE TITLE
where is the forum

### ISSUE THREAD

**Issue by rockstarrudy** [MobSpot/Code4Covid#7]
# where is it? @aboutDavid

**Comment by dispherical** [comment]
It's being setup @codersuntited .

**Comment by rockstarrudy** [comment]
@aboutDavid okay

**Comment by dispherical** [comment]
I'll edit this comment and tell you what going on with the forum.
Status: Installing apache2

**Comment by rockstarrudy** [comment]
@aboutDavid should I setup support emails

**Comment by dispherical** [comment]
> @aboutDavid should I setup support emails

?

**Comment by rockstarrudy** [comment]
@aboutDavid like support@code4covid.xyz

**Comment by rockstarrudy** [comment]
@aboutDavid what do u say?

**Comment by rockstarrudy** [comment]
@aboutDavid I can easily set it up. and you can have multiple emails]
# like
### support@code4covid.xyz
### join@code4covid.xyz
## etc
