### ISSUE TITLE
add me to the teams

### ISSUE THREAD

**Issue by rockstarrudy** [MobSpot/Code4Covid#8]
can I get invited to all the team
I would like to help with everything
@aboutDavid

**Comment by rockstarrudy** [comment]
Locked thread to only staff can see+reply

**Comment by rockstarrudy** [comment]
@aboutDavid also should I apply for discourse

**Comment by dispherical** [comment]
> @aboutDavid also should I apply for discourse

No.

**Comment by dispherical** [comment]
> can I get invited to all the team
> I would like to help with everything
> @aboutDavid

You are already in the team.
